### ISSUE TITLE
Hi do you know how to write a 3D convolutional autoencoder?

### ISSUE THREAD

**Issue by markofan** [nanopony/keras-convautoencoder#10]

**Comment by nanopony** [comment]
It should be similar to 2d autoencoder, but you should replace every 2d operation to its 3d equivalent. It might be tricky within traditional ML frameworks though, because of their intrinsic width x height x channel x sample_id dimensionality.  
Out of curiosity, are you from an academic field of research?

**Comment by markofan** [comment]
I am just a university student, recently I am doing a project and my data is 3D. So I have no choice but to use a 3D autoencoder.

**Comment by markofan** [comment]
I want to know that can I also use convolution when I'm doing decoding, can this autoenoder works well?

**Comment by nanopony** [comment]
This is 2d autoencoder, I've written a couple of custom layers for it to work - namely inverse layer for convolution and maxpool. 
Basically, you could look at how keras.layers.convolutional.Conv3D is implemented and try to make inverse layer for it. Then go for the same architecture.
I was curious about your task because I am MSc. in applied math and seek collaborations in ML :) So, if it is a research and there's a possibility of making a publication together, count me in :)

**Comment by nanopony** [comment]
Closing question due to inactivity of 2 weeks
